[workspace]
members = ["rcc_macros", "management"]

[package]
authors = ["LiangYongrui <leungyongrui@gmail.com>"]
name = "rcc"
version = "0.1.0"
edition = "2018"
description = """
rust cloud cache
fork from https://github.com/tokio-rs/rcc
"""

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
async-stream = "0.3"
atoi = "0.4"
bytes = "1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-futures = { version = "0.2" }
tracing-subscriber = "0.2"
chrono = { version = "0.4", features = ["serde"] }
automod = "1"
dashmap = { version = "4", features = ["serde"] }
rpds = { version = "0.9", features = ["serde"] }
nom = "6"
rcc_macros = { path = "./rcc_macros" }
nix = "0.22"
bincode = "1"
serde = { version = "1", features = ["derive"] }
serde_with = "1"
toml = "0.5"
once_cell = "1"
arc-swap = "1"

[dev-dependencies]
# Enable test-utilities in dev mode only. This is mostly for tests.
tokio = { version = "1", features = ["test-util"] }
