[package]
authors = ["LiangYongrui <leungyongrui@gmail.com>"]
name = "rcc"
version = "0.1.0"
edition = "2018"
description = """
rust cloud cache
fork from https://github.com/tokio-rs/mini-redis
"""

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
async-stream = "0.3"
atoi = "0.4"
bytes = "1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-futures = { version = "0.2" }
tracing-subscriber = "0.2"

[dev-dependencies]
# Enable test-utilities in dev mode only. This is mostly for tests.
tokio = { version = "1", features = ["test-util"] }

