[workspace]
members = ["rcc_macros", "management", "cmd_test", "component", "fixed_queue"]

[package]
authors = ["LiangYongrui <leungyongrui@gmail.com>"]
name = "rcc"
version = "0.1.0"
edition = "2018"
description = """
rust cloud cache
fork from https://github.com/tokio-rs/mini-redis
"""

[[bin]]
name = "server"
path = "./server/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
structopt = "0.3"
component = { path = "./component" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
