port = 5678
# replica = true
# master_addr = "127.0.0.1:1234"
forward_max_backlog = 100
max_connections = 500

[hdp]
# save_frequency = [[900, 1], [300, 10], [60, 10000]]
# save_hdp_dir = "./hdp"
# load_hdp_dir = "./hdp"
